/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PresidentRouteImport } from './routes/president'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesMatureRouteImport } from './routes/games.mature'
import { Route as GamesKidsRouteImport } from './routes/games.kids'
import { Route as GamesFamilyRouteImport } from './routes/games.family'

const PresidentRoute = PresidentRouteImport.update({
  id: '/president',
  path: '/president',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesMatureRoute = GamesMatureRouteImport.update({
  id: '/games/mature',
  path: '/games/mature',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesKidsRoute = GamesKidsRouteImport.update({
  id: '/games/kids',
  path: '/games/kids',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesFamilyRoute = GamesFamilyRouteImport.update({
  id: '/games/family',
  path: '/games/family',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/president': typeof PresidentRoute
  '/games/family': typeof GamesFamilyRoute
  '/games/kids': typeof GamesKidsRoute
  '/games/mature': typeof GamesMatureRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/president': typeof PresidentRoute
  '/games/family': typeof GamesFamilyRoute
  '/games/kids': typeof GamesKidsRoute
  '/games/mature': typeof GamesMatureRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/president': typeof PresidentRoute
  '/games/family': typeof GamesFamilyRoute
  '/games/kids': typeof GamesKidsRoute
  '/games/mature': typeof GamesMatureRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/president'
    | '/games/family'
    | '/games/kids'
    | '/games/mature'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/president'
    | '/games/family'
    | '/games/kids'
    | '/games/mature'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/president'
    | '/games/family'
    | '/games/kids'
    | '/games/mature'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PresidentRoute: typeof PresidentRoute
  GamesFamilyRoute: typeof GamesFamilyRoute
  GamesKidsRoute: typeof GamesKidsRoute
  GamesMatureRoute: typeof GamesMatureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/president': {
      id: '/president'
      path: '/president'
      fullPath: '/president'
      preLoaderRoute: typeof PresidentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/mature': {
      id: '/games/mature'
      path: '/games/mature'
      fullPath: '/games/mature'
      preLoaderRoute: typeof GamesMatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/kids': {
      id: '/games/kids'
      path: '/games/kids'
      fullPath: '/games/kids'
      preLoaderRoute: typeof GamesKidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/family': {
      id: '/games/family'
      path: '/games/family'
      fullPath: '/games/family'
      preLoaderRoute: typeof GamesFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PresidentRoute: PresidentRoute,
  GamesFamilyRoute: GamesFamilyRoute,
  GamesKidsRoute: GamesKidsRoute,
  GamesMatureRoute: GamesMatureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
